name: 'test_paypotes-server'

services:
  postgres:
    image: postgres:17-alpine
    container_name: test_postgres
    hostname: postgres
    ports:
      - "${POSTGRES_TEST_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  rabbitmq:
    image: rabbitmq:4-alpine
    container_name: test_rabbitmq
    hostname: rabbitmq
    ports:
      - "${RABBITMQ_TEST_PORT}:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - messaging

networks:
  messaging:
    name: test_messaging
    driver: bridge

volumes:
  postgres_data:
    name: test_paypot_postgres_data
  rabbitmq_data:
    name: test_paypot_rabbitmq_data