name: Node.js CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'yarn'

      - name: 🐳 Run containers
        run: |
          docker compose -f docker-compose.test.yml up -d
        env:
          RABBITMQ_HOST: 'localhost'
          RABBITMQ_TEST_PORT: '5673'
          RABBITMQ_DEFAULT_USER: 'test_paypot'
          RABBITMQ_DEFAULT_PASS: 'test_access'

      - name: 📦 Install dependencies
        run: yarn install

      - name: 👷 Build project
        run: yarn build

      - name: 🧑‍🔬 Run unit tests
        run: yarn test:ci

      - name: 🧑‍🔬 Run e2e tests
        run: yarn test:e2e:ci
        env:
          APP_ENVIRONMENT: 'test'
          RABBITMQ_HOST: 'localhost'
          RABBITMQ_TEST_PORT: '5673'
          RABBITMQ_DEFAULT_USER: 'test_paypot'
          RABBITMQ_DEFAULT_PASS: 'test_access'
          CONTACT_TASKS_QUEUE: 'test_contact_tasks'

      - name: 📝 Test summary
        uses: test-summary/action@v2
        with:
          paths: |
            test/reports/report-unit.xml
            test/reports/report-e2e.xml
          output: "test/results/summary.md"
        if: always()

      - name: 🐳 Stop containers
        run: |
          docker compose -f docker-compose.test.yml down