name: Node.js CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'yarn'

      - name: 📦 Install dependencies
        run: yarn install
        
  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'yarn'

      - name: 📦 Use cached dependencies
        run: yarn install

      - name: 👷 Build project
        run: yarn build

  test:
    needs: build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_DB: 'paypot'
    
      rabbitmq:
        image: rabbitmq:3
        ports:
          - 5673:5672
        env:
          RABBITMQ_DEFAULT_USER: 'test_paypot'
          RABBITMQ_DEFAULT_PASS: 'test_access'

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'yarn'

      - name: 📦 Use cached dependencies
        run: yarn install

      - name: 🧑‍🔬 Run unit tests
        run: yarn test

      - name: 🧑‍🔬 Run e2e tests
        run: yarn test:e2e
        env:
          APP_ENVIRONMENT: 'test'
          RABBITMQ_HOST: 'localhost'
          RABBITMQ_TEST_PORT: '5673'
          RABBITMQ_DEFAULT_USER: 'test_paypot'
          RABBITMQ_DEFAULT_PASS: 'test_access'
          CONTACT_TASKS_QUEUE: 'test_contact_tasks'
          POSTGRES_HOST: 'localhost'
          POSTGRES_TEST_PORT: '5433'
          POSTGRES_PORT: '5432'
          POSTGRES_DB: 'paypot'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
          DEFAULT_UUID: '46cd3732-f36e-4886-a2f8-1efebcda1ad6'
          POSTGRES_MIGRATIONS_PATH: '${{ github.workspace }}/dist/src/infrastructure/postgres/migrations'

      - name: 📝 Write test summary
        uses: test-summary/action@v2
        with:
          paths: |
            test/reports/report-unit.xml
            test/reports/report-e2e.xml
        if: always()